name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_IMAGE_NAME: dataesr/sandbox

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v3

      - name: 🏷️ Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: 🔑 Login Docker
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: 🐋 Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: 📦 Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ env.DOCKER_IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag ${{ env.DOCKER_IMAGE_NAME }} $IMAGE_ID:${{ steps.tag.outputs.tag }}
          docker tag ${{ env.DOCKER_IMAGE_NAME }} $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ steps.tag.outputs.tag }}
          docker push $IMAGE_ID:latest
